### ISSUE TITLE
Check that JmsSerializerBundle is enabled

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/resource-rest-bundle#10]
Throw useful exception if the JmsSerializerBundle is not present

**Comment by dantleech** [comment]
Also BazingaHateoasBundle

**Comment by dbu** [comment]
how do you want to do this? compiler pass? the generic solution is to make people use https://github.com/wjzijderveld/CheckBundles

not sure if we want something specific in just this bundle.

**Comment by dantleech** [comment]
Well, I think it is easy enough to do in the Extension. Just get the `kernel.bundles` and ensure that the bundle is registered.

**Comment by dantleech** [comment]
The CheckBundles script looks interesting though. But I wonder if checking in the Extension is more bullet proof.

**Comment by wouterj** [comment]
Btw, this is another case in favor of using FOSRestBundle :) (as it also provides fallbacks)

**Comment by dantleech** [comment]
@WouterJ do you know if FOSRestBundle provides a way to modify (i.e. add extra fields to) the response? One of the issues I see here is that we couple to JMS serializer in the Enhancer feature that I added. /cc @lsmith77

**Comment by lsmith77** [comment]
Well in FOSRestBundle you essentially create an instance of a View class which contains the data and some other pieces of information which is then converted either via a template or via a serializer into a response. As such if you have a View instance it can be placed into a Request attribute and then manipulated before it reaches the ViewHandler. BTW the ViewHandler is either called directly in the Controller or it is called automatically in a kernel view response event.

**Comment by dantleech** [comment]
What we are doing now is adding new fields _during_ the serialization process by hooking into the JMS serializer. I guess the FOSRestBundle wouldn't help here, as even if we added the information to the view, we would still need to recurisively add it to any nested Resources.

**Comment by lsmith77** [comment]
indeed .. the only "portable" approach would be to wrap objects rather than using serializer handler but this has limitations and is not so elegant. the core serializer is getting a lot of attention and is now configured as a readily available service in the FrameworkBundle .. so I think supporting it makes a lot of sense .. especially since JMS serializer is getting very little dev attention. but maybe in the end we just have to provide the code for 2 implementations. however if we do that .. then FOSRestBundle will definitely help a bit with the abstraction it provides, even if that abstraction will not cover everything.
