### ISSUE TITLE
Move SonataEnhancer to SonataAdminBundle

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/resource-rest-bundle#30]
I think we can move the SonataEnhancer to the SonataAdminBundle now that the TreeBrowser is officially integrated there.

It serves no purpose independently of that bundle (or?).

**Comment by wouterj** [comment]
Please note that I want to remove the direct TreeBrowserBundle integration from SonataDcotrine...AdminBundle. It was there because the complete backend Tree implementation was inside the admin bundle.

However, the backend part is now in the resource bundles. So we can safely move the tree form types to the TreeBrowserbundle, making them usefull for other admin integrations as well (or for instance the PHPCR browser).

It still doesn't make sense to use this enhancer without the SonataAdminBundle, so I would still vote to move it to there.

**Comment by dantleech** [comment]
'We can delete ther enhancer when we merge the "description enhancer" PR in ResourceBundle and adapt this bundle  to serialize that.

On 3 June 2016 23:14:53 BST, Wouter J notifications@github.com wrote:

> Please note that I want to remove direct TreeBrowserBundle integration
> from SonataDcotrine...AdminBundle. It was there because the complete
> backend Tree implementation was inside the admin bundle.
> 
> However, the backend part is now in the resource bundles. So we can
> safely move the tree form types to the TreeBrowserbundle, making them
> usefull for other admin integrations as well (or for instance the PHPCR
> browser).
> 
> It still doesn't make sense to use this enhancer without the
> SonataAdminBundle, so I would still vote to move it to there.
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/symfony-cmf/resource-rest-bundle/issues/30#issuecomment-223707544

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dbu** [comment]
> It still doesn't make sense to use this enhancer without the
> SonataAdminBundle, so I would still vote to move it to there.

the base bundle or the phpcr specific admin bundle?

**Comment by dantleech** [comment]
@dbu this issue was about moving the Enhancer to the PHPCR specific bundle (maybe not a good idea). But am closing this issue now as the Enhancer in this bundle will be effectively replaced by the new Enhancers that will be introduced in https://github.com/symfony-cmf/resource/pull/19.

Feel free to reopen if you disagree (although its the wrong issue to discuss)
