### ISSUE TITLE
Add node type to the response

### ISSUE THREAD

**Issue by wouterj** [symfony-cmf/resource-rest-bundle#7]
This can be used to (a) determine if a node can be edited, moved, etc and (b) to have different icons for each document type.

**Comment by dbu** [comment]
would this be the phpcr node type? or just the type of the "thing" at a path? phpcr node types are phpcr specific and do not apply to other things.

**Comment by dantleech** [comment]
This is something I left out as I didn't know the best way forward.

The most immediately obvious thing is to include the Resource FQCN. e.g.

```
type: Symfony\Cmf\Component\Resource\Repsitory\Resource\PhpcrOdmResource
```

But it also occurred to me to use aliases.

**Comment by dantleech** [comment]
I don't think, right now, that the tree browser side should be responsible for determining if a node should be moved, I think it would be better if that information was revealed through the webserivce.

Otherwise the tree browser would be responsible for tracking the mapping of the objects, when perhaps it should just be a very thin layer at the top.

**Comment by dantleech** [comment]
btw. Sling would defer to the Resource to get the type, e.g. if it were a PHPCR resource it would return the node type, if (for example) an ORM entity, the FCQN of the Entity.

**Comment by dbu** [comment]
i guess for the frontend, the type should just be a string with no semantic meaning about its contents. then it makes sense. short alias could be nice, e.g. for styling with css classes.

the decision what can be moved where belongs to the backend, but a frontend needs a way to retrieve that information as accurately as possible, to make drag and drop movement more user friendly.

**Comment by dantleech** [comment]
Maybe the TreeBrowser bundle can decorate the Rest response

**Comment by dantleech** [comment]
The problem is that while we can perhaps legitimately assign an FQCN alias to a Resource, it is out of scope to assign one to a Doctrine Entity FQCN as such information is "higher" then the resource bundle - it could be used in other contexts.

For example showing icons in a navigation breadcrumb or menu.

I had a look at this problem over christmas and created an ObjectInfoBundle.

https://github.com/dantleech/ObjectInfoBundle/blob/master/Tests/Resources/app/config/object-info.yml
https://github.com/dantleech/ObjectInfoBundle/blob/master/Tests/Functional/InfoManagerTest.php#L31

It is essentially a way to arbitrarily map and retrireve additional values to objects (either statically or dynamically). Became quite unsure about it though as it is perhaps _too_ arbitrary.

But maybe the solution right now would be to add some decorators to the resource rest bundle which add the information we need.

**Comment by dbu** [comment]
i like the idea of decorators. this must be flexible and pluggable, but should not get overly complicated.

**Comment by wouterj** [comment]
Fixed by https://github.com/symfony-cmf/ResourceRestBundle/pull/8 afaik
